import type { PlanTemplateDefinition } from './planTypes';

export const planTemplates: PlanTemplateDefinition[] = [
  {
    race: '5k',
    name: '5 km',
    minimumWeeks: 8,
    maximumWeeks: 16,
    preferredWeeks: 12,
    typicalWeeklyFoundationCount: 3,
    optionalWorkoutCount: { min: 0, max: 2 },
    minimumLongRunMinutes: 45,
    maximumLongRunMinutes: 90,
    foundationWorkoutMix: ['easy_run', 'long_run', 'strides', 'intervals', 'threshold'],
    emphasis: ['aerobic base', 'running economy', 'threshold support', 'controlled speed'],
  },
  {
    race: '10k',
    name: '10 km',
    minimumWeeks: 10,
    maximumWeeks: 18,
    preferredWeeks: 14,
    typicalWeeklyFoundationCount: 4,
    optionalWorkoutCount: { min: 0, max: 2 },
    minimumLongRunMinutes: 55,
    maximumLongRunMinutes: 105,
    foundationWorkoutMix: ['easy_run', 'long_run', 'threshold', 'intervals', 'race_pace'],
    emphasis: ['aerobic development', 'threshold capacity', '10k rhythm', 'late-race strength'],
  },
  {
    race: '15k',
    name: '15 km',
    minimumWeeks: 10,
    maximumWeeks: 20,
    preferredWeeks: 14,
    typicalWeeklyFoundationCount: 4,
    optionalWorkoutCount: { min: 0, max: 3 },
    minimumLongRunMinutes: 65,
    maximumLongRunMinutes: 120,
    foundationWorkoutMix: ['easy_run', 'long_run', 'threshold', 'tempo', 'race_pace'],
    emphasis: ['endurance', 'threshold strength', 'sustained race rhythm'],
  },
  {
    race: 'half_marathon',
    name: 'Half Marathon',
    minimumWeeks: 12,
    maximumWeeks: 24,
    preferredWeeks: 16,
    typicalWeeklyFoundationCount: 4,
    optionalWorkoutCount: { min: 1, max: 3 },
    minimumLongRunMinutes: 75,
    maximumLongRunMinutes: 150,
    foundationWorkoutMix: ['easy_run', 'long_run', 'threshold', 'tempo', 'race_pace'],
    emphasis: ['endurance durability', 'threshold development', 'race-pace control', 'fueling habits'],
  },
  {
    race: 'marathon',
    name: 'Marathon',
    minimumWeeks: 16,
    maximumWeeks: 24,
    preferredWeeks: 20,
    typicalWeeklyFoundationCount: 4,
    optionalWorkoutCount: { min: 1, max: 4 },
    minimumLongRunMinutes: 90,
    maximumLongRunMinutes: 210,
    foundationWorkoutMix: ['easy_run', 'long_run', 'threshold', 'tempo', 'race_pace'],
    emphasis: ['high consistency', 'long run development', 'fueling practice', 'marathon-specific endurance'],
  },
];
