import type { WorkoutDefinition } from './planTypes';

export const foundationWorkouts: WorkoutDefinition[] = [
  {
    id: 'easy_run',
    name: 'Easy Run',
    description: 'Relaxed aerobic running that should feel conversational and repeatable.',
    purpose: 'Build durable aerobic volume without excessive stress.',
    trainingEffect: 'Aerobic development, capillary density, musculoskeletal resilience.',
    typicalDuration: { minMinutes: 25, maxMinutes: 75 },
    intensity: 'easy',
    priority: 'foundation',
    category: 'aerobic',
    colourToken: 'workout.easy',
    icon: 'footprints',
    minimumRecoveryAfterHours: 12,
    canFollow: 'any',
    cannotFollow: [],
  },
  {
    id: 'recovery_run',
    name: 'Recovery Run',
    description: 'Short very easy run used to maintain rhythm while promoting recovery.',
    purpose: 'Increase frequency with minimal load after harder sessions.',
    trainingEffect: 'Circulation, movement quality, low-stress aerobic maintenance.',
    typicalDuration: { minMinutes: 15, maxMinutes: 45 },
    intensity: 'very_easy',
    priority: 'foundation',
    category: 'recovery',
    colourToken: 'workout.recovery',
    icon: 'leaf',
    minimumRecoveryAfterHours: 8,
    canFollow: 'any',
    cannotFollow: [],
  },
  {
    id: 'long_run',
    name: 'Long Run',
    description: 'The longest aerobic run of the week, progressed gradually.',
    purpose: 'Develop endurance, fuel efficiency, and confidence for race duration.',
    trainingEffect: 'Mitochondrial density, fatigue resistance, connective-tissue durability.',
    typicalDuration: { minMinutes: 45, maxMinutes: 210 },
    intensity: 'easy',
    priority: 'foundation',
    category: 'endurance',
    colourToken: 'workout.longRun',
    icon: 'route',
    minimumRecoveryAfterHours: 36,
    canFollow: ['easy_run', 'recovery_run', 'recovery_jog', 'walk', 'mobility'],
    cannotFollow: ['threshold', 'intervals', 'tempo', 'race_pace', 'hill_repeats'],
  },
  {
    id: 'threshold',
    name: 'Threshold',
    description: 'Controlled sustained work around comfortably-hard effort.',
    purpose: 'Improve lactate clearance and sustainable speed.',
    trainingEffect: 'Threshold development, aerobic power, fatigue resistance.',
    typicalDuration: { minMinutes: 35, maxMinutes: 75 },
    intensity: 'comfortably_hard',
    priority: 'foundation',
    category: 'threshold',
    colourToken: 'workout.threshold',
    icon: 'gauge',
    minimumRecoveryAfterHours: 36,
    canFollow: ['easy_run', 'recovery_run', 'recovery_jog', 'walk', 'mobility'],
    cannotFollow: ['threshold', 'intervals', 'tempo', 'race_pace', 'hill_repeats', 'long_run'],
  },
  {
    id: 'intervals',
    name: 'Intervals',
    description: 'Repeated faster efforts separated by recovery jogs or standing recoveries.',
    purpose: 'Develop speed, running economy, and aerobic power.',
    trainingEffect: 'VO2max stimulus, neuromuscular recruitment, race-speed familiarity.',
    typicalDuration: { minMinutes: 35, maxMinutes: 70 },
    intensity: 'hard',
    priority: 'foundation',
    category: 'speed',
    colourToken: 'workout.intervals',
    icon: 'zap',
    minimumRecoveryAfterHours: 40,
    canFollow: ['easy_run', 'recovery_run', 'recovery_jog', 'walk', 'mobility'],
    cannotFollow: ['threshold', 'intervals', 'tempo', 'race_pace', 'hill_repeats', 'long_run'],
  },
  {
    id: 'tempo',
    name: 'Tempo',
    description: 'Steady moderate-to-strong run below all-out race effort.',
    purpose: 'Bridge easy endurance and harder threshold work.',
    trainingEffect: 'Aerobic strength, rhythm, sustainable mechanics under mild fatigue.',
    typicalDuration: { minMinutes: 30, maxMinutes: 80 },
    intensity: 'moderate',
    priority: 'foundation',
    category: 'threshold',
    colourToken: 'workout.tempo',
    icon: 'metronome',
    minimumRecoveryAfterHours: 30,
    canFollow: ['easy_run', 'recovery_run', 'recovery_jog', 'walk', 'mobility'],
    cannotFollow: ['threshold', 'intervals', 'tempo', 'race_pace', 'hill_repeats'],
  },
  {
    id: 'race_pace',
    name: 'Race Pace',
    description: 'Specific practice at planned race effort within a controlled session.',
    purpose: 'Sharpen pacing skill and race-specific efficiency.',
    trainingEffect: 'Specific endurance, pacing confidence, economy at goal effort.',
    typicalDuration: { minMinutes: 30, maxMinutes: 100 },
    intensity: 'race_specific',
    priority: 'foundation',
    category: 'race_specific',
    colourToken: 'workout.racePace',
    icon: 'flag',
    minimumRecoveryAfterHours: 36,
    canFollow: ['easy_run', 'recovery_run', 'recovery_jog', 'walk', 'mobility'],
    cannotFollow: ['threshold', 'intervals', 'tempo', 'race_pace', 'hill_repeats', 'long_run'],
  },
  {
    id: 'hill_repeats',
    name: 'Hill Repeats',
    description: 'Short uphill repetitions emphasizing power, posture, and controlled effort.',
    purpose: 'Build strength and running economy with lower impact speed work.',
    trainingEffect: 'Neuromuscular power, stride mechanics, strength endurance.',
    typicalDuration: { minMinutes: 30, maxMinutes: 60 },
    intensity: 'hard',
    priority: 'foundation',
    category: 'strength',
    colourToken: 'workout.hills',
    icon: 'mountain',
    minimumRecoveryAfterHours: 36,
    canFollow: ['easy_run', 'recovery_run', 'recovery_jog', 'walk', 'mobility'],
    cannotFollow: ['threshold', 'intervals', 'tempo', 'race_pace', 'hill_repeats', 'long_run'],
  },
  {
    id: 'strides',
    name: 'Strides',
    description: 'Brief relaxed accelerations attached to easy running.',
    purpose: 'Maintain speed touch without turning the day into a hard workout.',
    trainingEffect: 'Neuromuscular coordination, running economy, leg turnover.',
    typicalDuration: { minMinutes: 20, maxMinutes: 55 },
    intensity: 'moderate',
    priority: 'foundation',
    category: 'speed',
    colourToken: 'workout.strides',
    icon: 'fast-forward',
    minimumRecoveryAfterHours: 16,
    canFollow: ['easy_run', 'recovery_run', 'recovery_jog', 'walk', 'mobility'],
    cannotFollow: ['intervals', 'race_pace', 'hill_repeats'],
  },
];

export const optionalWorkouts: WorkoutDefinition[] = [
  {
    id: 'recovery_jog',
    name: 'Recovery Jog',
    description: 'Very short jog when the athlete wants extra movement.',
    purpose: 'Support consistency without adding meaningful stress.',
    trainingEffect: 'Gentle circulation and habit reinforcement.',
    typicalDuration: { minMinutes: 10, maxMinutes: 30 },
    intensity: 'very_easy',
    priority: 'optional',
    category: 'recovery',
    colourToken: 'workout.optionalRecovery',
    icon: 'leaf',
    minimumRecoveryAfterHours: 6,
    canFollow: 'any',
    cannotFollow: [],
  },
  {
    id: 'shakeout',
    name: 'Shakeout',
    description: 'Brief relaxed movement before a race or key workout day.',
    purpose: 'Reduce stiffness and rehearse relaxed mechanics.',
    trainingEffect: 'Neuromuscular priming with negligible training load.',
    typicalDuration: { minMinutes: 10, maxMinutes: 25 },
    intensity: 'very_easy',
    priority: 'optional',
    category: 'recovery',
    colourToken: 'workout.shakeout',
    icon: 'sparkles',
    minimumRecoveryAfterHours: 6,
    canFollow: 'any',
    cannotFollow: [],
  },
  {
    id: 'easy_double',
    name: 'Easy Double',
    description: 'Second short easy run on the same day for experienced athletes.',
    purpose: 'Add aerobic volume while keeping each run manageable.',
    trainingEffect: 'Frequency and aerobic volume with controlled mechanical load.',
    typicalDuration: { minMinutes: 15, maxMinutes: 45 },
    intensity: 'easy',
    priority: 'optional',
    category: 'aerobic',
    colourToken: 'workout.easyDouble',
    icon: 'repeat',
    minimumRecoveryAfterHours: 12,
    canFollow: ['easy_run', 'recovery_run'],
    cannotFollow: ['threshold', 'intervals', 'tempo', 'race_pace', 'hill_repeats', 'long_run'],
  },
  {
    id: 'cross_training',
    name: 'Cross Training',
    description: 'Low-impact aerobic work such as cycling, swimming, or elliptical.',
    purpose: 'Add aerobic stimulus while reducing running impact.',
    trainingEffect: 'Aerobic maintenance and supplemental endurance.',
    typicalDuration: { minMinutes: 20, maxMinutes: 75 },
    intensity: 'easy',
    priority: 'optional',
    category: 'aerobic',
    colourToken: 'workout.crossTraining',
    icon: 'bike',
    minimumRecoveryAfterHours: 8,
    canFollow: 'any',
    cannotFollow: [],
  },
  {
    id: 'walk',
    name: 'Walk',
    description: 'Easy walking used for active recovery or habit continuity.',
    purpose: 'Promote movement on non-running days.',
    trainingEffect: 'Low-intensity circulation and recovery support.',
    typicalDuration: { minMinutes: 10, maxMinutes: 60 },
    intensity: 'very_easy',
    priority: 'optional',
    category: 'recovery',
    colourToken: 'workout.walk',
    icon: 'person-standing',
    minimumRecoveryAfterHours: 0,
    canFollow: 'any',
    cannotFollow: [],
  },
  {
    id: 'mobility',
    name: 'Mobility',
    description: 'Light mobility, activation, or gentle strength maintenance.',
    purpose: 'Support range of motion and tissue readiness.',
    trainingEffect: 'Movement quality and recovery support.',
    typicalDuration: { minMinutes: 10, maxMinutes: 35 },
    intensity: 'very_easy',
    priority: 'optional',
    category: 'mobility',
    colourToken: 'workout.mobility',
    icon: 'stretch-horizontal',
    minimumRecoveryAfterHours: 0,
    canFollow: 'any',
    cannotFollow: [],
  },
];

export const workoutLibrary: WorkoutDefinition[] = [...foundationWorkouts, ...optionalWorkouts];
