import { NavLink } from 'react-router-dom';
import { colors, fontFamily, icons, radius, shadows, spacing, theme, typography } from '../../design';
import type { CSSProperties, ReactNode } from 'react';

const px = (value: number) => `${value}px`;

type ButtonProps = { children: ReactNode; onClick?: () => void; type?: 'button' | 'submit'; disabled?: boolean };
const buttonBase: CSSProperties = { ...typography.button, border: 0, borderRadius: radius.button, cursor: 'pointer', minHeight: px(52), padding: `${px(spacing.md)} ${px(spacing.lg)}`, transition: `transform ${theme.animation.fast}, background ${theme.animation.fast}, opacity ${theme.animation.fast}` };
export function PrimaryButton(props: ButtonProps) { return <button {...props} style={{ ...buttonBase, background: colors.primary.green, color: colors.neutral.white, boxShadow: shadows.card, opacity: props.disabled ? 0.6 : 1 }}>{props.children}</button>; }
export function SecondaryButton(props: ButtonProps) { return <button {...props} style={{ ...buttonBase, background: colors.neutral.surface, color: colors.neutral.text, border: `1px solid ${colors.neutral.border}` }}>{props.children}</button>; }

export function PageContainer({ children }: { children: ReactNode }) { return <div style={{ maxWidth: px(theme.layout.maxWidth), margin: '0 auto', minHeight: '100vh', background: colors.neutral.surfaceWarm, boxShadow: shadows.shell, padding: `${px(spacing.pageTop)} ${px(spacing.pageX)} calc(env(safe-area-inset-bottom) + ${px(spacing.navBottom)})` }}>{children}</div>; }
export function Header() { return <header style={{ marginBottom: px(spacing.lg) }}><p style={{ ...typography.caption, color: colors.neutral.muted, textTransform: 'uppercase', letterSpacing: '0.22em', margin: 0 }}>Life-Fit</p><h1 style={{ ...typography.h1, color: colors.neutral.text, margin: `${px(spacing.xs)} 0 0` }}>Running Coach</h1></header>; }
export function ScreenTitle({ eyebrow, title, children }: { eyebrow?: string; title: string; children?: ReactNode }) { return <div style={{ marginBottom: px(spacing.md) }}>{eyebrow ? <p style={{ ...typography.caption, color: colors.neutral.muted, margin: 0, textTransform: 'uppercase' }}>{eyebrow}</p> : null}<h2 style={{ ...typography.h2, color: colors.neutral.text, margin: `${px(spacing.xs)} 0 0` }}>{title}</h2>{children ? <p style={{ ...typography.small, color: colors.neutral.muted, margin: `${px(spacing.xs)} 0 0` }}>{children}</p> : null}</div>; }
export function SectionCard({ children }: { children: ReactNode }) { return <section style={{ background: colors.neutral.surface, border: `1px solid ${colors.neutral.border}`, borderRadius: radius.card, boxShadow: shadows.card, padding: px(spacing.lg) }}>{children}</section>; }

const workoutMap = { easy: [colors.primary.greenTint, colors.primary.green], threshold: [colors.accent.purpleTint, colors.accent.purple], longRun: [colors.accent.orangeTint, colors.accent.orange], recovery: [colors.accent.skyTint, colors.accent.sky], optional: [colors.neutral.faint, colors.neutral.muted], extra: [colors.accent.slateTint, colors.accent.slate] } as const;
export type WorkoutTone = keyof typeof workoutMap;
export function WorkoutCard({ title, meta, tone = 'easy' }: { title: string; meta: string; tone?: WorkoutTone }) { const [bg, fg] = workoutMap[tone]; return <SectionCard><div style={{ display: 'flex', justifyContent: 'space-between', gap: px(spacing.md), alignItems: 'center' }}><div><p style={{ ...typography.caption, color: fg, margin: 0, textTransform: 'uppercase' }}>{tone}</p><h3 style={{ ...typography.h3, color: colors.neutral.text, margin: `${px(spacing.xs)} 0 0` }}>{title}</h3><p style={{ ...typography.small, color: colors.neutral.muted, margin: `${px(spacing.xs)} 0 0` }}>{meta}</p></div><span style={{ background: bg, color: fg, borderRadius: radius.chip, padding: `${px(spacing.xs)} ${px(spacing.sm)}`, ...typography.caption }}>Run</span></div></SectionCard>; }
export function ProgressBar({ value }: { value: number }) { return <div style={{ height: px(spacing.xs), background: colors.neutral.faint, borderRadius: radius.chip, overflow: 'hidden' }}><div style={{ width: `${Math.max(0, Math.min(100, value))}%`, height: '100%', background: colors.primary.green, borderRadius: radius.chip }} /></div>; }

const statusMap = { completed: [colors.primary.greenTint, colors.primary.green, 'Completed'], moved: [colors.accent.amberTint, colors.accent.amber, 'Moved'], notPlanned: [colors.neutral.faint, colors.neutral.muted, 'Not Planned'], foundation: [colors.neutral.surface, colors.primary.green, 'Foundation'], optional: [colors.neutral.surface, colors.accent.sky, 'Optional'], extra: [colors.neutral.surface, colors.accent.purple, 'Extra'] } as const;
export type StatusTone = keyof typeof statusMap;
export function StatusChip({ tone }: { tone: StatusTone }) { const [bg, fg, label] = statusMap[tone]; return <span style={{ ...typography.caption, display: 'inline-flex', borderRadius: radius.chip, padding: `${px(spacing.xs)} ${px(spacing.sm)}`, color: fg, background: bg, border: `1px solid ${fg}` }}>{label}</span>; }
export function EmptyState({ title, children }: { title: string; children: ReactNode }) { return <SectionCard><div style={{ textAlign: 'center', padding: `${px(spacing.lg)} 0` }}><div style={{ color: colors.primary.green, fontSize: px(spacing.xl) }}>{icons.empty}</div><h3 style={{ ...typography.h3, margin: `${px(spacing.sm)} 0 ${px(spacing.xs)}` }}>{title}</h3><p style={{ ...typography.small, color: colors.neutral.muted, margin: 0 }}>{children}</p></div></SectionCard>; }
export function Divider() { return <hr style={{ border: 0, borderTop: `1px solid ${colors.neutral.border}`, margin: `${px(spacing.lg)} 0` }} />; }
export function InfoBanner({ children }: { children: ReactNode }) { return <div style={{ ...typography.small, color: colors.accent.sky, background: colors.accent.skyTint, borderRadius: radius.card, padding: px(spacing.md), border: `1px solid ${colors.accent.sky}` }}>{children}</div>; }
export function PlaceholderSkeleton() { return <div style={{ display: 'grid', gap: px(spacing.sm) }}><div style={{ height: px(spacing.lg), background: colors.neutral.faint, borderRadius: radius.skeleton }} /><div style={{ height: px(spacing.md), width: '72%', background: colors.neutral.faint, borderRadius: radius.skeleton }} /></div>; }
export function LoadingSpinner() { return <div aria-label="Loading" style={{ width: px(spacing.xl), height: px(spacing.xl), borderRadius: radius.chip, border: `3px solid ${colors.neutral.faint}`, borderTopColor: colors.primary.green }} />; }

const navItems = [{ to: '/today', label: 'Today', icon: icons.today }, { to: '/week', label: 'Week', icon: icons.week }, { to: '/settings', label: 'Settings', icon: icons.settings }];
export function BottomNavigation() { return <nav style={{ position: 'fixed', left: '50%', bottom: 0, transform: 'translateX(-50%)', width: '100%', maxWidth: px(theme.layout.maxWidth), background: 'rgba(255,255,255,0.96)', borderTop: `1px solid ${colors.neutral.border}`, boxShadow: shadows.nav, padding: `${px(spacing.sm)} ${px(spacing.md)} calc(env(safe-area-inset-bottom) + ${px(spacing.sm)})`, fontFamily }}><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: px(spacing.xs) }}>{navItems.map((item) => <NavLink key={item.to} to={item.to} style={({ isActive }) => ({ ...typography.caption, textAlign: 'center', borderRadius: radius.nav, padding: px(spacing.sm), color: isActive ? colors.neutral.white : colors.neutral.muted, background: isActive ? colors.primary.green : colors.neutral.surface })}><span style={{ display: 'block' }}>{item.icon}</span>{item.label}</NavLink>)}</div></nav>; }
