import { NavLink } from 'react-router-dom';
import { colors, fontFamily, icons, radius, shadows, spacing, theme, typography } from '../../design';
import type { CSSProperties, InputHTMLAttributes, ReactNode } from 'react';

const px = (value: number) => `${value}px`;
const stack = (gap: number = spacing.md): CSSProperties => ({ display: 'grid', gap: px(gap) });

type ButtonProps = { children: ReactNode; onClick?: () => void; type?: 'button' | 'submit'; disabled?: boolean };
const buttonBase: CSSProperties = { ...typography.button, border: 0, borderRadius: radius.button, cursor: 'pointer', minHeight: px(52), padding: `${px(spacing.md)} ${px(spacing.lg)}`, transition: `transform ${theme.animation.fast}, background ${theme.animation.fast}, opacity ${theme.animation.fast}`, width: '100%' };
export function PrimaryButton(props: ButtonProps) { return <button {...props} style={{ ...buttonBase, background: colors.primary.green, color: colors.neutral.white, boxShadow: shadows.card, opacity: props.disabled ? 0.6 : 1 }}>{props.children}</button>; }
export function SecondaryButton(props: ButtonProps) { return <button {...props} style={{ ...buttonBase, background: colors.neutral.surface, color: colors.neutral.text, border: `1px solid ${colors.neutral.border}` }}>{props.children}</button>; }

export function PageContainer({ children }: { children: ReactNode }) { return <div style={{ maxWidth: px(theme.layout.maxWidth), margin: '0 auto', minHeight: '100vh', background: colors.neutral.surfaceWarm, boxShadow: shadows.shell, padding: `${px(spacing.pageTop)} ${px(spacing.pageX)} calc(env(safe-area-inset-bottom) + ${px(spacing.navBottom)})` }}>{children}</div>; }
export function Header() { return <header style={{ marginBottom: px(spacing.lg) }}><p style={{ ...typography.caption, color: colors.neutral.muted, textTransform: 'uppercase', letterSpacing: '0.22em', margin: 0 }}>Life-Fit</p><h1 style={{ ...typography.h1, color: colors.neutral.text, margin: `${px(spacing.xs)} 0 0` }}>Running Coach</h1></header>; }
export function ScreenTitle({ eyebrow, title, children }: { eyebrow?: string; title: string; children?: ReactNode }) { return <div style={{ marginBottom: px(spacing.md) }}>{eyebrow ? <p style={{ ...typography.caption, color: colors.neutral.muted, margin: 0, textTransform: 'uppercase' }}>{eyebrow}</p> : null}<h2 style={{ ...typography.h2, color: colors.neutral.text, margin: `${px(spacing.xs)} 0 0` }}>{title}</h2>{children ? <p style={{ ...typography.small, color: colors.neutral.muted, margin: `${px(spacing.xs)} 0 0` }}>{children}</p> : null}</div>; }
export function HeroTitle({ eyebrow, title, children }: { eyebrow?: string; title: string; children?: ReactNode }) { return <div style={{ ...stack(spacing.sm), marginBottom: px(spacing.lg) }}>{eyebrow ? <p style={{ ...typography.caption, color: colors.neutral.muted, margin: 0, textTransform: 'uppercase' }}>{eyebrow}</p> : null}<h2 style={{ ...typography.display, color: colors.neutral.text, margin: 0 }}>{title}</h2>{children ? <p style={{ ...typography.body, color: colors.neutral.muted, margin: 0 }}>{children}</p> : null}</div>; }
export function SectionCard({ children }: { children: ReactNode }) { return <section style={{ background: colors.neutral.surface, border: `1px solid ${colors.neutral.border}`, borderRadius: radius.card, boxShadow: shadows.card, padding: px(spacing.lg) }}>{children}</section>; }

export function SlidePanel({ isOpen, title, subtitle, children, onClose }: { isOpen: boolean; title: string; subtitle?: string; children: ReactNode; onClose: () => void }) {
  return <div style={{ position: 'fixed', inset: 0, zIndex: 20, pointerEvents: isOpen ? 'auto' : 'none', overflow: 'hidden' }} aria-hidden={!isOpen}>
    <button type="button" aria-label="Close panel" onClick={onClose} style={{ position: 'absolute', inset: 0, width: '100%', border: 0, background: isOpen ? 'rgba(47,42,36,0.18)' : 'rgba(47,42,36,0)', transition: `background ${theme.animation.page}` }} />
    <aside role="dialog" aria-modal="true" aria-label={title} style={{ position: 'absolute', top: 0, right: 0, width: '85vw', maxWidth: px(Math.round(theme.layout.maxWidth * 0.85)), height: '100%', background: colors.neutral.surfaceWarm, borderTopLeftRadius: radius.card, borderBottomLeftRadius: radius.card, boxShadow: shadows.shell, transform: isOpen ? 'translateX(0)' : 'translateX(100%)', transition: `transform ${theme.animation.page}`, display: 'grid', gridTemplateRows: 'auto minmax(0, 1fr)', overflow: 'hidden' }}>
      <header style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) auto', gap: px(spacing.sm), alignItems: 'start', padding: `${px(spacing.md)} ${px(spacing.md)} ${px(spacing.sm)}`, borderBottom: `1px solid ${colors.neutral.border}`, background: colors.neutral.surface }}>
        <div style={{ minWidth: 0 }}>
          <h2 style={{ ...typography.h3, margin: 0, overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{title}</h2>
          {subtitle ? <p style={{ ...typography.small, color: colors.neutral.muted, margin: `${px(spacing.xxs)} 0 0` }}>{subtitle}</p> : null}
        </div>
        <button type="button" aria-label="Close" onClick={onClose} style={{ ...buttonBase, minHeight: px(36), width: px(36), padding: 0, background: colors.neutral.surface, color: colors.neutral.text, border: `1px solid ${colors.neutral.border}`, boxShadow: 'none' }}>×</button>
      </header>
      <div style={{ overflowY: 'auto', overflowX: 'hidden', padding: `${px(spacing.md)} ${px(spacing.md)} calc(env(safe-area-inset-bottom) + ${px(spacing.navBottom)})` }}>{children}</div>
    </aside>
  </div>;
}

export function PageStack({ children }: { children: ReactNode }) { return <div style={stack(spacing.lg)}>{children}</div>; }
export function CardStack({ children }: { children: ReactNode }) { return <div style={stack(spacing.md)}>{children}</div>; }
export function IllustrationPlaceholder({ children }: { children: ReactNode }) { return <div style={{ minHeight: px(180), borderRadius: radius.card, background: colors.primary.greenTint, border: `1px solid ${colors.neutral.border}`, display: 'grid', placeItems: 'center', color: colors.primary.green, ...typography.h1, textAlign: 'center', padding: px(spacing.xl) }}>{children}</div>; }
export function StatCard({ label, value, detail }: { label: string; value: string; detail?: string }) { return <SectionCard><p style={{ ...typography.caption, color: colors.neutral.muted, margin: 0, textTransform: 'uppercase' }}>{label}</p><p style={{ ...typography.h2, color: colors.neutral.text, margin: `${px(spacing.xs)} 0 0` }}>{value}</p>{detail ? <p style={{ ...typography.small, color: colors.neutral.muted, margin: `${px(spacing.xs)} 0 0` }}>{detail}</p> : null}</SectionCard>; }
export function Chip({ children, tone = 'neutral' }: { children: ReactNode; tone?: 'neutral' | 'green' | 'sky' | 'purple' | 'orange' }) { const map = { neutral: [colors.neutral.faint, colors.neutral.muted], green: [colors.primary.greenTint, colors.primary.green], sky: [colors.accent.skyTint, colors.accent.sky], purple: [colors.accent.purpleTint, colors.accent.purple], orange: [colors.accent.orangeTint, colors.accent.orange] } as const; const [bg, fg] = map[tone]; return <span style={{ ...typography.caption, display: 'inline-flex', width: 'fit-content', borderRadius: radius.chip, padding: `${px(spacing.xs)} ${px(spacing.sm)}`, color: fg, background: bg }}>{children}</span>; }
export function TextArea({ placeholder }: { placeholder: string }) { return <textarea placeholder={placeholder} style={{ ...typography.body, width: '100%', minHeight: px(120), boxSizing: 'border-box', resize: 'vertical', border: `1px solid ${colors.neutral.border}`, borderRadius: radius.input, padding: px(spacing.md), color: colors.neutral.text, background: colors.neutral.surface }} />; }
export function TextInput(props: InputHTMLAttributes<HTMLInputElement>) { return <input {...props} style={{ ...typography.body, width: '100%', boxSizing: 'border-box', minHeight: px(56), border: `1px solid ${colors.neutral.border}`, borderRadius: radius.input, padding: px(spacing.md), color: colors.neutral.text, background: colors.neutral.surface }} />; }

const workoutMap = { easy: [colors.primary.greenTint, colors.primary.green], threshold: [colors.accent.purpleTint, colors.accent.purple], longRun: [colors.accent.orangeTint, colors.accent.orange], recovery: [colors.accent.skyTint, colors.accent.sky], optional: [colors.neutral.faint, colors.neutral.muted], extra: [colors.accent.slateTint, colors.accent.slate] } as const;
export type WorkoutTone = keyof typeof workoutMap;
export function WorkoutCard({ title, meta, tone = 'easy' }: { title: string; meta: string; tone?: WorkoutTone }) { const [bg, fg] = workoutMap[tone]; return <SectionCard><div style={{ display: 'flex', justifyContent: 'space-between', gap: px(spacing.md), alignItems: 'center' }}><div><p style={{ ...typography.caption, color: fg, margin: 0, textTransform: 'uppercase' }}>{tone}</p><h3 style={{ ...typography.h3, color: colors.neutral.text, margin: `${px(spacing.xs)} 0 0` }}>{title}</h3><p style={{ ...typography.small, color: colors.neutral.muted, margin: `${px(spacing.xs)} 0 0` }}>{meta}</p></div><span style={{ background: bg, color: fg, borderRadius: radius.chip, padding: `${px(spacing.xs)} ${px(spacing.sm)}`, ...typography.caption }}>Run</span></div></SectionCard>; }
export function ProgressBar({ value }: { value: number }) { return <div style={{ height: px(spacing.xs), background: colors.neutral.faint, borderRadius: radius.chip, overflow: 'hidden' }}><div style={{ width: `${Math.max(0, Math.min(100, value))}%`, height: '100%', background: colors.primary.green, borderRadius: radius.chip }} /></div>; }

const statusMap = { completed: [colors.primary.greenTint, colors.primary.green, 'Completed'], moved: [colors.accent.amberTint, colors.accent.amber, 'Moved'], notPlanned: [colors.neutral.faint, colors.neutral.muted, 'Not Planned'], foundation: [colors.neutral.surface, colors.primary.green, 'Foundation'], optional: [colors.neutral.surface, colors.accent.sky, 'Optional'], extra: [colors.neutral.surface, colors.accent.purple, 'Extra'] } as const;
export type StatusTone = keyof typeof statusMap;
export function StatusChip({ tone }: { tone: StatusTone }) { const [bg, fg, label] = statusMap[tone]; return <span style={{ ...typography.caption, display: 'inline-flex', borderRadius: radius.chip, padding: `${px(spacing.xs)} ${px(spacing.sm)}`, color: fg, background: bg, border: `1px solid ${fg}` }}>{label}</span>; }
export function EmptyState({ title, children }: { title: string; children: ReactNode }) { return <SectionCard><div style={{ textAlign: 'center', padding: `${px(spacing.lg)} 0` }}><div style={{ color: colors.primary.green, fontSize: px(spacing.xl) }}>{icons.empty}</div><h3 style={{ ...typography.h3, margin: `${px(spacing.sm)} 0 ${px(spacing.xs)}` }}>{title}</h3><p style={{ ...typography.small, color: colors.neutral.muted, margin: 0 }}>{children}</p></div></SectionCard>; }
export function Divider() { return <hr style={{ border: 0, borderTop: `1px solid ${colors.neutral.border}`, margin: `${px(spacing.lg)} 0` }} />; }
export function InfoBanner({ children }: { children: ReactNode }) { return <div style={{ ...typography.small, color: colors.accent.sky, background: colors.accent.skyTint, borderRadius: radius.card, padding: px(spacing.md), border: `1px solid ${colors.accent.sky}` }}>{children}</div>; }
export function PlaceholderSkeleton() { return <div style={stack(spacing.sm)}><div style={{ height: px(spacing.lg), background: colors.neutral.faint, borderRadius: radius.skeleton }} /><div style={{ height: px(spacing.md), width: '72%', background: colors.neutral.faint, borderRadius: radius.skeleton }} /></div>; }
export function LoadingSpinner() { return <div aria-label="Loading" style={{ width: px(spacing.xl), height: px(spacing.xl), borderRadius: radius.chip, border: `3px solid ${colors.neutral.faint}`, borderTopColor: colors.primary.green }} />; }

const navItems = [{ to: '/today', label: 'Today', icon: icons.today }, { to: '/week', label: 'Week', icon: icons.week }, { to: '/settings', label: 'Settings', icon: icons.settings }];
export function BottomNavigation() { return <nav style={{ position: 'fixed', left: '50%', bottom: 0, transform: 'translateX(-50%)', width: '100%', maxWidth: px(theme.layout.maxWidth), background: 'rgba(255,255,255,0.96)', borderTop: `1px solid ${colors.neutral.border}`, boxShadow: shadows.nav, padding: `${px(spacing.sm)} ${px(spacing.md)} calc(env(safe-area-inset-bottom) + ${px(spacing.sm)})`, fontFamily }}><div style={{ display: 'grid', gridTemplateColumns: 'repeat(3, 1fr)', gap: px(spacing.xs) }}>{navItems.map((item) => <NavLink key={item.to} to={item.to} style={({ isActive }) => ({ ...typography.caption, textAlign: 'center', borderRadius: radius.nav, padding: px(spacing.sm), color: isActive ? colors.neutral.white : colors.neutral.muted, background: isActive ? colors.primary.green : colors.neutral.surface })}><span style={{ display: 'block' }}>{item.icon}</span>{item.label}</NavLink>)}</div></nav>; }
